server:
    port: 8765
spring:
    application:
        name: zuul-service

eureka:
    client:
        registerWithEureka: true
        fetchRegistry: true
        availabilityZones:
            default: ${APPLICATION_DOMAIN:${DOMAIN:defaultZone}}
    serviceUrl:
        defaultZone: ${vcap.services.sessionqaeureka.credentials.uri:http://localhost:8761/eureka}
    instance:
        leaseRenewalIntervalInSeconds: 50
        leaseExpirationDurationInSeconds: 30
        preferlpAddress: false
        statusPageUrlPath: /info
        healthCheckUrlPath: /health

zuul:
    routes:
        product-service:
            serviceId: product-service
            path: /product-service/**
        order-service:
            serviceId: order-service
            path: /order-service/**            
#        loadbalance-service:
#            serviceId: loadbalance-service
#            path: /**           