server:
    port: 2221
spring:
    application:
        name: product-service

eureka:
    client:
        registerWithEureka: true
        fetchRegistry: true
        availabilityZones:
            default: ${APPLICATION_DOMAIN:${DOMAIN:defaultZone}}
    serviceUrl:
        defaultZone: ${vcap.services.sessionqaeureka.credentials.uri:http://localhost:8761/eureka}
    instance:
        leaseRenewalIntervalInSeconds: 50
        leaseExpirationDurationInSeconds: 30
        preferlpAddress: false
        statusPageUrlPath: /info
        healthCheckUrlPath: /health